/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFormField: typeof import('./src/components/AppFormField.vue')['default']
    AppInfoCard: typeof import('./src/components/AppInfoCard.vue')['default']
    AppMdiIcon: typeof import('./src/components/AppMdiIcon.vue')['default']
    AppMobileNav: typeof import('./src/components/AppMobileNav.vue')['default']
    AppMonacoEditor: typeof import('./src/components/AppMonacoEditor.vue')['default']
    AppNumberField: typeof import('./src/components/AppNumberField.vue')['default']
    AppPanel: typeof import('./src/components/AppPanel.vue')['default']
    AppRecordCard: typeof import('./src/components/AppRecordCard.vue')['default']
    AppRecordHeader: typeof import('./src/components/AppRecordHeader.vue')['default']
    AppRouteBreadcrumbs: typeof import('./src/components/AppRouteBreadcrumbs.vue')['default']
    AppSelectField: typeof import('./src/components/AppSelectField.vue')['default']
    AppSettingsBlock: typeof import('./src/components/AppSettingsBlock.vue')['default']
    AppSettingsSection: typeof import('./src/components/AppSettingsSection.vue')['default']
    AppSidebar: typeof import('./src/components/AppSidebar.vue')['default']
    AppSidebarContent: typeof import('./src/components/AppSidebarContent.vue')['default']
    AppStateMessage: typeof import('./src/components/AppStateMessage.vue')['default']
    AppTableToolbar: typeof import('./src/components/AppTableToolbar.vue')['default']
    AppTextField: typeof import('./src/components/AppTextField.vue')['default']
    AppToggleField: typeof import('./src/components/AppToggleField.vue')['default']
    AppToggleGroup: typeof import('./src/components/AppToggleGroup.vue')['default']
    AsyncStateBlock: typeof import('./src/components/AsyncStateBlock.vue')['default']
    Button: typeof import('primevue/button')['default']
    EmptyState: typeof import('./src/components/EmptyState.vue')['default']
    EntityDialog: typeof import('./src/components/EntityDialog.vue')['default']
    LibraryCreateFolderDialog: typeof import('./src/components/LibraryCreateFolderDialog.vue')['default']
    LibraryCreateTextFileDialog: typeof import('./src/components/LibraryCreateTextFileDialog.vue')['default']
    LibraryMoveDialog: typeof import('./src/components/LibraryMoveDialog.vue')['default']
    LibraryPreviewContent: typeof import('./src/components/LibraryPreviewContent.vue')['default']
    LibraryPreviewPanel: typeof import('./src/components/LibraryPreviewPanel.vue')['default']
    LibraryPreviewShell: typeof import('./src/components/LibraryPreviewShell.vue')['default']
    LibraryResourceCards: typeof import('./src/components/LibraryResourceCards.vue')['default']
    LibraryResourceTable: typeof import('./src/components/LibraryResourceTable.vue')['default']
    LibraryToolbar: typeof import('./src/components/LibraryToolbar.vue')['default']
    LibraryTreePane: typeof import('./src/components/LibraryTreePane.vue')['default']
    MemberDialog: typeof import('./src/components/MemberDialog.vue')['default']
    MemberManagementSection: typeof import('./src/components/MemberManagementSection.vue')['default']
    ProjectFilesPanel: typeof import('./src/components/ProjectFilesPanel.vue')['default']
    ProjectSourceFolderDialog: typeof import('./src/components/ProjectSourceFolderDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchForm: typeof import('./src/components/SearchForm.vue')['default']
    SearchHistoryPanel: typeof import('./src/components/SearchHistoryPanel.vue')['default']
    SearchResultList: typeof import('./src/components/SearchResultList.vue')['default']
    SearchSelectionPreview: typeof import('./src/components/SearchSelectionPreview.vue')['default']
    SettingsAccessTokensSection: typeof import('./src/components/settings-sections/SettingsAccessTokensSection.vue')['default']
    SettingsAdminUsersSection: typeof import('./src/components/settings-sections/SettingsAdminUsersSection.vue')['default']
    SettingsAppearanceSection: typeof import('./src/components/settings-sections/SettingsAppearanceSection.vue')['default']
    SettingsDoclingSection: typeof import('./src/components/settings-sections/SettingsDoclingSection.vue')['default']
    SettingsRuntimeSection: typeof import('./src/components/settings-sections/SettingsRuntimeSection.vue')['default']
    SettingsSearchSection: typeof import('./src/components/settings-sections/SettingsSearchSection.vue')['default']
    SourceEditorForm: typeof import('./src/components/SourceEditorForm.vue')['default']
    SourceTable: typeof import('./src/components/SourceTable.vue')['default']
  }
}
