/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooterTools: typeof import('./src/components/AppFooterTools.vue')['default']
    AppFormField: typeof import('./src/components/AppFormField.vue')['default']
    AppInfoCard: typeof import('./src/components/AppInfoCard.vue')['default']
    AppMonacoEditor: typeof import('./src/components/AppMonacoEditor.vue')['default']
    AppNumberField: typeof import('./src/components/AppNumberField.vue')['default']
    AppNumberPresetField: typeof import('./src/components/AppNumberPresetField.vue')['default']
    AppPanel: typeof import('./src/components/AppPanel.vue')['default']
    AppRecordCard: typeof import('./src/components/AppRecordCard.vue')['default']
    AppRecordHeader: typeof import('./src/components/AppRecordHeader.vue')['default']
    AppSelectField: typeof import('./src/components/AppSelectField.vue')['default']
    AppSettingsSection: typeof import('./src/components/AppSettingsSection.vue')['default']
    AppSidebar: typeof import('./src/components/AppSidebar.vue')['default']
    AppStateMessage: typeof import('./src/components/AppStateMessage.vue')['default']
    AppTableToolbar: typeof import('./src/components/AppTableToolbar.vue')['default']
    AppTextField: typeof import('./src/components/AppTextField.vue')['default']
    AppToggleField: typeof import('./src/components/AppToggleField.vue')['default']
    AppToggleGroup: typeof import('./src/components/AppToggleGroup.vue')['default']
    AsyncStateBlock: typeof import('./src/components/AsyncStateBlock.vue')['default']
    EmptyState: typeof import('./src/components/EmptyState.vue')['default']
    LibraryCreateFolderDialog: typeof import('./src/components/LibraryCreateFolderDialog.vue')['default']
    LibraryMoveDialog: typeof import('./src/components/LibraryMoveDialog.vue')['default']
    LibraryPreviewContent: typeof import('./src/components/LibraryPreviewContent.vue')['default']
    LibraryPreviewPanel: typeof import('./src/components/LibraryPreviewPanel.vue')['default']
    LibraryPreviewShell: typeof import('./src/components/LibraryPreviewShell.vue')['default']
    LibraryResourceTable: typeof import('./src/components/LibraryResourceTable.vue')['default']
    LibraryToolbar: typeof import('./src/components/LibraryToolbar.vue')['default']
    LibraryTreePane: typeof import('./src/components/LibraryTreePane.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchForm: typeof import('./src/components/SearchForm.vue')['default']
    SearchResultList: typeof import('./src/components/SearchResultList.vue')['default']
    SettingsDoclingSection: typeof import('./src/components/settings-sections/SettingsDoclingSection.vue')['default']
    SettingsRuntimeSection: typeof import('./src/components/settings-sections/SettingsRuntimeSection.vue')['default']
    SettingsSearchSection: typeof import('./src/components/settings-sections/SettingsSearchSection.vue')['default']
    SourceEditorForm: typeof import('./src/components/SourceEditorForm.vue')['default']
    SourceTable: typeof import('./src/components/SourceTable.vue')['default']
  }
}
