import type { components } from "../../generated/openapi";

type Schemas = components["schemas"];

export type ApiErrorResponse = Schemas["ApiErrorResponse"];
export type AdminUserResponse = Schemas["AdminUserResponse"];
export type AdminUserPageQuery = Schemas["AdminUserPageQuery"];
export type AdminUserPageResponse = Schemas["AdminUserPageResponse"];
export type AuthLoginRequest = Schemas["AuthLoginRequest"];
export type AuthMeResponse = Schemas["AuthMeResponse"];
export type AuthUserResponse = Schemas["AuthUserResponse"];
export type CreateAdminUserRequest = Schemas["CreateAdminUserRequest"];
export type CreateFolderRequest = Schemas["CreateFolderRequest"];
export type CreateGroupRequest = Schemas["CreateGroupRequest"];
export type CreatePersonalAccessTokenRequest = Schemas["CreatePersonalAccessTokenRequest"];
export type CreatePersonalAccessTokenResponse = Schemas["CreatePersonalAccessTokenResponse"];
export type CreateSourceFolderRequest = Schemas["CreateSourceFolderRequest"];
export type DoclingSettingsResponse = Schemas["DoclingSettingsResponse"];
export type DocumentChunkResponse = Schemas["DocumentChunkResponse"];
export type DocumentResponse = Schemas["DocumentResponse"];
export type CreateMetadataIndexRequest = Schemas["CreateMetadataIndexRequest"];
export type MetadataIndexResponse = Schemas["MetadataIndexResponse"];
export type UpdateMetadataIndexRequest = Schemas["UpdateMetadataIndexRequest"];
export type DocumentQueryRequest = Schemas["DocumentQueryRequest"];
export type DocumentQueryResponse = Schemas["DocumentQueryResponse"];
export type BatchGetDocumentsRequest = Schemas["BatchGetDocumentsRequest"];
export type BatchGetDocumentsResponse = Schemas["BatchGetDocumentsResponse"];
export type GroupMemberResponse = Schemas["GroupMemberResponse"];
export type GroupMemberPageResponse = Schemas["GroupMemberPageResponse"];
export type GroupPageResponse = Schemas["GroupPageResponse"];
export type GroupSearchQuery = Schemas["GroupSearchQuery"];
export type GroupKind = Schemas["GroupKind"];
export type GroupResponse = Schemas["GroupResponse"];
export type HealthResponse = Schemas["HealthResponse"];
export type LibraryDocumentSectionPreview = Schemas["LibraryDocumentSectionPreview"];
export type LibraryFileDetailResponse = Schemas["LibraryFileDetailResponse"];
export type LibraryFileSummary = Schemas["LibraryFileSummary"];
export type LibraryFolderNode = Schemas["LibraryFolderNode"];
export type LibraryFolderResponse = Schemas["LibraryFolderResponse"];
export type LibraryIngestJobResponse = Schemas["LibraryIngestJobResponse"];
export type LibraryIngestStatus = Schemas["LibraryIngestStatus"];
export type LibraryPreviewContentFormat = Schemas["LibraryPreviewContentFormat"];
export type LibraryResourceItem = Schemas["LibraryResourceItem"];
export type LibraryResourcePageResponse = Schemas["LibraryResourcePageResponse"];
export type LibraryResourceSortBy = Schemas["LibraryResourceSortBy"];
export type SortDirection = Schemas["SortDirection"];
export type LibraryTreeResponse = Schemas["LibraryTreeResponse"];
export type LibraryUploadResponse = Schemas["LibraryUploadResponse"];
export type MoveFileRequest = Schemas["MoveFileRequest"];
export type MoveFolderRequest = Schemas["MoveFolderRequest"];
export type MoveGroupRequest = Schemas["MoveGroupRequest"];
export type MembershipRole = Schemas["MembershipRole"];
export type NamespacePageQuery = Schemas["NamespacePageQuery"];
export type PersonalAccessTokenResponse = Schemas["PersonalAccessTokenResponse"];
export type PersonalAccessTokenScope = Schemas["PersonalAccessTokenScope"];
export type PrepareLibraryUploadRequest = Schemas["PrepareLibraryUploadRequest"];
export type PrepareLibraryUploadResponse = Schemas["PrepareLibraryUploadResponse"];
export type ResetAdminUserPasswordRequest = Schemas["ResetAdminUserPasswordRequest"];
export type RuntimeSettingsResponse = Schemas["RuntimeSettingsResponse"];
export type SearchHit = Schemas["SearchHit"];
export type SearchMode = Schemas["SearchMode"];
export type SearchRequest = Schemas["SearchRequest"];
export type SearchResponse = Schemas["SearchResponse"];
export type SearchSettingsResponse = Schemas["SearchSettingsResponse"];
export type SourceConfigInput = Schemas["SourceConfigInput"];
export type SourceConnectionResponse = Schemas["SourceConnectionResponse"];
export type SourceFolderResponse = Schemas["SourceFolderResponse"];
export type SourceStatus = Schemas["SourceStatus"];
export type SyncOutcome = Schemas["SyncOutcome"];
export type UpdateAdminUserRequest = Schemas["UpdateAdminUserRequest"];
export type UpdateDoclingSettingsRequest = Schemas["UpdateDoclingSettingsRequest"];
export type UpdateGroupRequest = Schemas["UpdateGroupRequest"];
export type UpdateRuntimeSettingsRequest = Schemas["UpdateRuntimeSettingsRequest"];
export type UpdateRuntimeS3Settings = Schemas["UpdateRuntimeS3Settings"];
export type TestRuntimeValkeyRequest = Schemas["TestRuntimeValkeyRequest"];
export type UpdateSearchSettingsRequest = Schemas["UpdateSearchSettingsRequest"];
export type UpsertLibraryTextRequest = Schemas["UpsertLibraryTextRequest"];
export type UpsertMembershipRequest = Schemas["UpsertMembershipRequest"];
export type UpsertSourceConnectionRequest = Schemas["UpsertSourceConnectionRequest"];
export type UserDirectoryEntryResponse = Schemas["UserDirectoryEntryResponse"];
export type Visibility = Schemas["Visibility"];
export type VectorIndexRebuildStatus = Schemas["VectorIndexRebuildStatus"];
export type TranslationSettingsResponse = Schemas["TranslationSettingsResponse"];
export type UpdateTranslationSettingsRequest = Schemas["UpdateTranslationSettingsRequest"];
export type TranslationProviderInput = Schemas["TranslationProviderInput"];
export type TranslationProviderResponse = Schemas["TranslationProviderResponse"];
export type GroupTranslationSettingsResponse = Schemas["GroupTranslationSettingsResponse"];
export type UpdateGroupTranslationSettingsRequest = Schemas["UpdateGroupTranslationSettingsRequest"];

export interface RequestOptions {
  signal?: AbortSignal;
}

export type ApiResult<TData> = {
  data?: TData;
  error?: unknown;
  response: Response;
};
