import type { components } from "../../generated/openapi";

type Schemas = components["schemas"];

export type ApiErrorResponse = Schemas["ApiErrorResponse"];
export type AdminUserResponse = Schemas["AdminUserResponse"];
export type AdminUserPageQuery = Schemas["AdminUserPageQuery"];
export type AdminUserPageResponse = Schemas["AdminUserPageResponse"];
export type AdminUserSortBy = Schemas["AdminUserSortBy"];
export type Pagination = Schemas["Pagination"];
export type AuthLoginRequest = Schemas["AuthLoginRequest"];
export type AuthMeResponse = Schemas["AuthMeResponse"];
export type AuthUserResponse = Schemas["AuthUserResponse"];
export type CancelActiveTasksResponse = Schemas["CancelActiveTasksResponse"];
export type CreateAdminUserRequest = Schemas["CreateAdminUserRequest"];
export type CreateFolderRequest = Schemas["CreateFolderRequest"];
export type CreateGroupRequest = Schemas["CreateGroupRequest"];
export type CreatePersonalAccessTokenRequest = Schemas["CreatePersonalAccessTokenRequest"];
export type CreatePersonalAccessTokenResponse = Schemas["CreatePersonalAccessTokenResponse"];
export type CreateSourceFolderRequest = Schemas["CreateSourceFolderRequest"];
export type DoclingSettingsResponse = Schemas["DoclingSettingsResponse"];
export type DocumentChunkResponse = Schemas["DocumentChunkResponse"];
export type DocumentResponse = Schemas["DocumentResponse"];
export type CreateMetadataIndexRequest = Schemas["CreateMetadataIndexRequest"];
export type MetadataIndexResponse = Schemas["MetadataIndexResponse"];
export type UpdateMetadataIndexRequest = Schemas["UpdateMetadataIndexRequest"];
export type DocumentQueryRequest = Schemas["DocumentQueryRequest"];
export type DocumentQueryResponse = Schemas["DocumentQueryResponse"];
export type BatchGetDocumentsRequest = Schemas["BatchGetDocumentsRequest"];
export type BatchGetDocumentsResponse = Schemas["BatchGetDocumentsResponse"];
export type GroupMemberResponse = Schemas["GroupMemberResponse"];
export type GroupMemberPageResponse = Schemas["GroupMemberPageResponse"];
export type GroupPageResponse = Schemas["GroupPageResponse"];
export type GroupSearchQuery = Schemas["GroupSearchQuery"];
export type GroupSortBy = Schemas["GroupSortBy"];
export type MemberPageQuery = Schemas["MemberPageQuery"];
export type MemberSortBy = Schemas["MemberSortBy"];
export type GroupKind = Schemas["GroupKind"];
export type GroupResponse = Schemas["GroupResponse"];
export type HealthResponse = Schemas["HealthResponse"];
export type LibraryDocumentSectionPreview = Schemas["LibraryDocumentSectionPreview"];
export type LibraryFileDetailResponse = Schemas["LibraryFileDetailResponse"];
export type LibraryFileSummary = Schemas["LibraryFileSummary"];
export type LibraryFolderNode = Schemas["LibraryFolderNode"];
export type LibraryFolderResponse = Schemas["LibraryFolderResponse"];
export type LibraryIngestFailureStage = Schemas["LibraryIngestFailureStage"];
export type LibraryIngestStatus = Schemas["LibraryIngestStatus"];
export type LibraryPreviewContentFormat = Schemas["LibraryPreviewContentFormat"];
export type LibraryResourceItem = Schemas["LibraryResourceItem"];
export type LibraryResourcePageResponse = Schemas["LibraryResourcePageResponse"];
export type LibraryResourceSortBy = Schemas["LibraryResourceSortBy"];
export type SortDirection = Schemas["SortDirection"];
export type LibraryTreeResponse = Schemas["LibraryTreeResponse"];
export type MoveFileRequest = Schemas["MoveFileRequest"];
export type MoveFolderRequest = Schemas["MoveFolderRequest"];
export type MoveGroupRequest = Schemas["MoveGroupRequest"];
export type MembershipRole = Schemas["MembershipRole"];
export type NamespacePageQuery = Schemas["NamespacePageQuery"];
export type PersonalAccessTokenResponse = Schemas["PersonalAccessTokenResponse"];
export type PersonalAccessTokenScope = Schemas["PersonalAccessTokenScope"];
export type PrepareLibraryUploadRequest = Schemas["PrepareLibraryUploadRequest"];
export type PrepareLibraryUploadResponse = Schemas["PrepareLibraryUploadResponse"];
export type PurgeTasksRequest = Schemas["PurgeTasksRequest"];
export type PurgeTasksResponse = Schemas["PurgeTasksResponse"];
export type ResetAdminUserPasswordRequest = Schemas["ResetAdminUserPasswordRequest"];
export type RuntimeSettingsResponse = Schemas["RuntimeSettingsResponse"];
export type SearchHit = Schemas["SearchHit"];
export type SearchMode = Schemas["SearchMode"];
export type SearchRequest = Schemas["SearchRequest"];
export type SearchResponse = Schemas["SearchResponse"];
export type SearchSettingsResponse = Schemas["SearchSettingsResponse"];
export type SourceConfigInput = Schemas["SourceConfigInput"];
export type SourceConnectionResponse = Schemas["SourceConnectionResponse"];
export type SourceFolderResponse = Schemas["SourceFolderResponse"];
export type SourceStatus = Schemas["SourceStatus"];
export type SourcePageResponse = Schemas["SourcePageResponse"];
export type MetadataIndexPageResponse = Schemas["MetadataIndexPageResponse"];
export type PersonalAccessTokenPageResponse = Schemas["PersonalAccessTokenPageResponse"];
export type SyncOutcome = Schemas["SyncOutcome"];
export type UpdateAdminUserRequest = Schemas["UpdateAdminUserRequest"];
export type UpdateTaskMaintenanceSettingsRequest = Schemas["UpdateTaskMaintenanceSettingsRequest"];
export type UpdateDoclingSettingsRequest = Schemas["UpdateDoclingSettingsRequest"];
export type UpdateGroupRequest = Schemas["UpdateGroupRequest"];
export type TaskSubmitRequest = Schemas["TaskSubmitRequest"];
export type FileRetryItem = Schemas["FileRetryItem"];
export type TaskKind = Schemas["TaskKind"];
export type TaskMaintenanceOverview = Schemas["TaskMaintenanceOverview"];
export type TaskMaintenanceSettings = Schemas["TaskMaintenanceSettings"];
export type TaskMaintenanceStats = Schemas["TaskMaintenanceStats"];
export type TaskPurgeMode = Schemas["TaskPurgeMode"];
export type TaskStatus = Schemas["TaskStatus"];
export type TaskItemStatus = Schemas["TaskItemStatus"];
export type TaskSortBy = Schemas["TaskSortBy"];
export type TaskListQuery = Schemas["TaskListQuery"];
export type TaskPageResponse = Schemas["TaskPageResponse"];
export type TaskResponse = Schemas["TaskResponse"];
export type TaskItemsResponse = Schemas["TaskItemsResponse"];
export type TaskRetryResponse = Schemas["TaskRetryResponse"];
export type RerunTaskResponse = Schemas["RerunTaskResponse"];
export type TaskRef = Schemas["TaskRef"];
export type RecoverDoclingTaskRequest = Schemas["RecoverDoclingTaskRequest"];
export type RecoverDoclingTaskResponse = Schemas["RecoverDoclingTaskResponse"];
export type UpdateRuntimeSettingsRequest = Schemas["UpdateRuntimeSettingsRequest"];
export type UpdateRuntimeS3Settings = Schemas["UpdateRuntimeS3Settings"];
export type TestRuntimeValkeyRequest = Schemas["TestRuntimeValkeyRequest"];
export type UpdateSearchSettingsRequest = Schemas["UpdateSearchSettingsRequest"];
export type UpsertLibraryTextRequest = Schemas["UpsertLibraryTextRequest"];
export type UpsertMembershipRequest = Schemas["UpsertMembershipRequest"];
export type UpsertSourceConnectionRequest = Schemas["UpsertSourceConnectionRequest"];
export type UserDirectoryEntryResponse = Schemas["UserDirectoryEntryResponse"];
export type Visibility = Schemas["Visibility"];
export type TranslationSettingsResponse = Schemas["TranslationSettingsResponse"];
export type UpdateTranslationSettingsRequest = Schemas["UpdateTranslationSettingsRequest"];
export type TranslationProviderInput = Schemas["TranslationProviderInput"];
export type TranslationProviderResponse = Schemas["TranslationProviderResponse"];
export type TranslationProviderPageResponse = Schemas["TranslationProviderPageResponse"];
export type GroupTranslationSettingsResponse = Schemas["GroupTranslationSettingsResponse"];
export type UpdateGroupTranslationSettingsRequest = Schemas["UpdateGroupTranslationSettingsRequest"];

export interface RequestOptions {
  signal?: AbortSignal;
}

export type ApiResult<TData> = {
  data?: TData;
  error?: unknown;
  response: Response;
};

export type PageRequest = {
  page: number;
  page_size: number;
};

export type PaginatedResponse<T> = {
  items: T[];
  pagination: Pagination;
};
