//! Mechanical OpenAPI operation manifest (Redmine 362 Task 4b, sdk-raw).
//!
//! Generated mechanically from `frontend/openapi/context69.openapi.json`
//! (114 operations, sorted by `operation_id` for deterministic diffs).
//! Do not edit by hand; regenerate from OpenAPI so contract tests can compare
//! `operation_id`/`method`/`path` exactly. `request_schema`/`response_schema`
//! name the shared contract schemas (`-` means no JSON body/response,
//! `multipart-form` means `multipart/form-data`, `array<T>` means a JSON array).
//! `requires_auth=false` matches the router public routes (`/healthz`,
//! `/v1/auth/login`, `/v1/auth/logout` outside `auth_middleware`); every other
//! operation requires a personal access token. `idempotent=true` marks the
//! task-submitting operations that honor `Idempotency-Key`.

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum BodyKind {
    Empty,
    Json,
    Multipart,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Operation {
    pub id: &'static str,
    pub method: &'static str,
    pub path_template: &'static str,
    pub requires_auth: bool,
    pub body_kind: BodyKind,
    pub request_schema: &'static str,
    pub response_schema: &'static str,
    pub success_status: u16,
    pub idempotent: bool,
}

pub const OPERATIONS: &[Operation] = &[
    Operation {
        id: "batch_get_group_documents",
        method: "POST",
        path_template: "/v1/groups/by-path/{group_path}/documents/batch-get",
        requires_auth: true,
        body_kind: BodyKind::Json,
        request_schema: "BatchGetDocumentsRequest",
        response_schema: "BatchGetDocumentsResponse",
        success_status: 200,
        idempotent: false,
    },
    Operation {
        id: "cancel_active_tasks",
        method: "POST",
        path_template: "/v1/admin/tasks/cancel-active",
        requires_auth: true,
        body_kind: BodyKind::Empty,
        request_schema: "-",
        response_schema: "CancelActiveTasksResponse",
        success_status: 200,
        idempotent: false,
    },
    Operation {
        id: "cancel_task",
        method: "POST",
        path_template: "/v1/tasks/{task_id}/cancel",
        requires_auth: true,
        body_kind: BodyKind::Empty,
        request_schema: "-",
        response_schema: "-",
        success_status: 204,
        idempotent: false,
    },
    Operation {
        id: "clear_task_history",
        method: "POST",
        path_template: "/v1/tasks/clear",
        requires_auth: true,
        body_kind: BodyKind::Json,
        request_schema: "ClearTaskHistoryRequest",
        response_schema: "ClearTaskHistoryResponse",
        success_status: 200,
        idempotent: false,
    },
    Operation {
        id: "create_admin_user",
        method: "POST",
        path_template: "/v1/admin/users",
        requires_auth: true,
        body_kind: BodyKind::Json,
        request_schema: "CreateAdminUserRequest",
        response_schema: "AdminUserResponse",
        success_status: 201,
        idempotent: false,
    },
    Operation {
        id: "create_group",
        method: "POST",
        path_template: "/v1/groups",
        requires_auth: true,
        body_kind: BodyKind::Json,
        request_schema: "CreateGroupRequest",
        response_schema: "GroupResponse",
        success_status: 201,
        idempotent: false,
    },
    Operation {
        id: "create_group_library_folder",
        method: "POST",
        path_template: "/v1/groups/by-path/{group_path}/library/folders",
        requires_auth: true,
        body_kind: BodyKind::Json,
        request_schema: "CreateFolderRequest",
        response_schema: "LibraryFolderResponse",
        success_status: 201,
        idempotent: false,
    },
    Operation {
        id: "create_group_library_text",
        method: "POST",
        path_template: "/v1/groups/by-path/{group_path}/library/texts",
        requires_auth: true,
        body_kind: BodyKind::Json,
        request_schema: "CreateTextRequest",
        response_schema: "TaskRef",
        success_status: 202,
        idempotent: false,
    },
    Operation {
        id: "create_group_source_folder",
        method: "POST",
        path_template: "/v1/groups/by-path/{group_path}/source-folders",
        requires_auth: true,
        body_kind: BodyKind::Json,
        request_schema: "CreateSourceFolderRequest",
        response_schema: "SourceFolderResponse",
        success_status: 201,
        idempotent: false,
    },
    Operation {
        id: "create_library_folder",
        method: "POST",
        path_template: "/v1/library/folders",
        requires_auth: true,
        body_kind: BodyKind::Json,
        request_schema: "CreateFolderRequest",
        response_schema: "LibraryFolderResponse",
        success_status: 201,
        idempotent: false,
    },
    Operation {
        id: "create_library_text",
        method: "POST",
        path_template: "/v1/library/texts",
        requires_auth: true,
        body_kind: BodyKind::Json,
        request_schema: "CreateTextRequest",
        response_schema: "TaskRef",
        success_status: 202,
        idempotent: false,
    },
    Operation {
        id: "create_metadata_index",
        method: "POST",
        path_template: "/v1/groups/by-path/{group_path}/metadata-indexes",
        requires_auth: true,
        body_kind: BodyKind::Json,
        request_schema: "CreateMetadataIndexRequest",
        response_schema: "MetadataIndexResponse",
        success_status: 201,
        idempotent: false,
    },
    Operation {
        id: "create_personal_access_token",
        method: "POST",
        path_template: "/v1/auth/personal-access-tokens",
        requires_auth: true,
        body_kind: BodyKind::Json,
        request_schema: "CreatePersonalAccessTokenRequest",
        response_schema: "CreatePersonalAccessTokenResponse",
        success_status: 200,
        idempotent: false,
    },
    Operation {
        id: "create_source",
        method: "POST",
        path_template: "/v1/sources",
        requires_auth: true,
        body_kind: BodyKind::Json,
        request_schema: "SourceConfigInput",
        response_schema: "SourceStatus",
        success_status: 201,
        idempotent: false,
    },
    Operation {
        id: "create_source_connection",
        method: "POST",
        path_template: "/v1/source-connections",
        requires_auth: true,
        body_kind: BodyKind::Json,
        request_schema: "UpsertSourceConnectionRequest",
        response_schema: "SourceConnectionResponse",
        success_status: 200,
        idempotent: false,
    },
    Operation {
        id: "delete_group",
        method: "DELETE",
        path_template: "/v1/groups/by-path/{group_path}",
        requires_auth: true,
        body_kind: BodyKind::Empty,
        request_schema: "-",
        response_schema: "-",
        success_status: 204,
        idempotent: false,
    },
    Operation {
        id: "delete_group_document_by_key",
        method: "DELETE",
        path_template: "/v1/groups/by-path/{group_path}/documents/by-external-id",
        requires_auth: true,
        body_kind: BodyKind::Empty,
        request_schema: "-",
        response_schema: "TaskRef",
        success_status: 202,
        idempotent: false,
    },
    Operation {
        id: "delete_group_library_file",
        method: "DELETE",
        path_template: "/v1/groups/by-path/{group_path}/library/files/{file_id}",
        requires_auth: true,
        body_kind: BodyKind::Empty,
        request_schema: "-",
        response_schema: "TaskRef",
        success_status: 202,
        idempotent: false,
    },
    Operation {
        id: "delete_group_library_folder",
        method: "DELETE",
        path_template: "/v1/groups/by-path/{group_path}/library/folders/{folder_id}",
        requires_auth: true,
        body_kind: BodyKind::Empty,
        request_schema: "-",
        response_schema: "TaskRef",
        success_status: 202,
        idempotent: false,
    },
    Operation {
        id: "delete_group_member",
        method: "DELETE",
        path_template: "/v1/groups/by-path/{group_path}/members/{login_name}",
        requires_auth: true,
        body_kind: BodyKind::Empty,
        request_schema: "-",
        response_schema: "-",
        success_status: 204,
        idempotent: false,
    },
    Operation {
        id: "delete_library_file",
        method: "DELETE",
        path_template: "/v1/library/files/{file_id}",
        requires_auth: true,
        body_kind: BodyKind::Empty,
        request_schema: "-",
        response_schema: "TaskRef",
        success_status: 202,
        idempotent: false,
    },
    Operation {
        id: "delete_library_folder",
        method: "DELETE",
        path_template: "/v1/library/folders/{folder_id}",
        requires_auth: true,
        body_kind: BodyKind::Empty,
        request_schema: "-",
        response_schema: "TaskRef",
        success_status: 202,
        idempotent: false,
    },
    Operation {
        id: "delete_metadata_index",
        method: "DELETE",
        path_template: "/v1/groups/by-path/{group_path}/metadata-indexes/{index_id}",
        requires_auth: true,
        body_kind: BodyKind::Empty,
        request_schema: "-",
        response_schema: "-",
        success_status: 204,
        idempotent: false,
    },
    Operation {
        id: "delete_source",
        method: "DELETE",
        path_template: "/v1/sources/{source_key}",
        requires_auth: true,
        body_kind: BodyKind::Empty,
        request_schema: "-",
        response_schema: "-",
        success_status: 204,
        idempotent: false,
    },
    Operation {
        id: "delete_source_connection",
        method: "DELETE",
        path_template: "/v1/source-connections/{name}",
        requires_auth: true,
        body_kind: BodyKind::Empty,
        request_schema: "-",
        response_schema: "-",
        success_status: 204,
        idempotent: false,
    },
    Operation {
        id: "delete_task",
        method: "DELETE",
        path_template: "/v1/tasks/{task_id}",
        requires_auth: true,
        body_kind: BodyKind::Empty,
        request_schema: "-",
        response_schema: "-",
        success_status: 204,
        idempotent: false,
    },
    Operation {
        id: "disable_admin_user",
        method: "POST",
        path_template: "/v1/admin/users/{login_name}/disable",
        requires_auth: true,
        body_kind: BodyKind::Empty,
        request_schema: "-",
        response_schema: "AdminUserResponse",
        success_status: 200,
        idempotent: false,
    },
    Operation {
        id: "enable_admin_user",
        method: "POST",
        path_template: "/v1/admin/users/{login_name}/enable",
        requires_auth: true,
        body_kind: BodyKind::Empty,
        request_schema: "-",
        response_schema: "AdminUserResponse",
        success_status: 200,
        idempotent: false,
    },
    Operation {
        id: "ensure_scope",
        method: "POST",
        path_template: "/v1/scopes/ensure",
        requires_auth: true,
        body_kind: BodyKind::Json,
        request_schema: "ScopeSpec",
        response_schema: "EnsureScopeResponse",
        success_status: 200,
        idempotent: false,
    },
    Operation {
        id: "get_docling_settings",
        method: "GET",
        path_template: "/v1/settings/docling",
        requires_auth: true,
        body_kind: BodyKind::Empty,
        request_schema: "-",
        response_schema: "DoclingSettingsResponse",
        success_status: 200,
        idempotent: false,
    },
    Operation {
        id: "get_document",
        method: "GET",
        path_template: "/v1/documents/{document_id}",
        requires_auth: true,
        body_kind: BodyKind::Empty,
        request_schema: "-",
        response_schema: "DocumentResponse",
        success_status: 200,
        idempotent: false,
    },
    Operation {
        id: "get_extraction_health",
        method: "GET",
        path_template: "/v1/admin/extraction/health",
        requires_auth: true,
        body_kind: BodyKind::Empty,
        request_schema: "-",
        response_schema: "ExtractionHealthResponse",
        success_status: 200,
        idempotent: false,
    },
    Operation {
        id: "get_group",
        method: "GET",
        path_template: "/v1/groups/by-path/{group_path}",
        requires_auth: true,
        body_kind: BodyKind::Empty,
        request_schema: "-",
        response_schema: "GroupResponse",
        success_status: 200,
        idempotent: false,
    },
    Operation {
        id: "get_group_document_by_key",
        method: "GET",
        path_template: "/v1/groups/by-path/{group_path}/documents/by-external-id",
        requires_auth: true,
        body_kind: BodyKind::Empty,
        request_schema: "-",
        response_schema: "DocumentResponse",
        success_status: 200,
        idempotent: false,
    },
    Operation {
        id: "get_group_library_file",
        method: "GET",
        path_template: "/v1/groups/by-path/{group_path}/library/files/{file_id}",
        requires_auth: true,
        body_kind: BodyKind::Empty,
        request_schema: "-",
        response_schema: "LibraryFileDetailResponse",
        success_status: 200,
        idempotent: false,
    },
    Operation {
        id: "get_group_library_resources",
        method: "GET",
        path_template: "/v1/groups/by-path/{group_path}/library/resources",
        requires_auth: true,
        body_kind: BodyKind::Empty,
        request_schema: "-",
        response_schema: "LibraryResourcePageResponse",
        success_status: 200,
        idempotent: false,
    },
    Operation {
        id: "get_group_library_tree",
        method: "GET",
        path_template: "/v1/groups/by-path/{group_path}/library/tree",
        requires_auth: true,
        body_kind: BodyKind::Empty,
        request_schema: "-",
        response_schema: "LibraryTreeResponse",
        success_status: 200,
        idempotent: false,
    },
    Operation {
        id: "get_group_translation_settings",
        method: "GET",
        path_template: "/v1/groups/by-path/{group_path}/translation-settings",
        requires_auth: true,
        body_kind: BodyKind::Empty,
        request_schema: "-",
        response_schema: "GroupTranslationSettingsResponse",
        success_status: 200,
        idempotent: false,
    },
    Operation {
        id: "get_library_file",
        method: "GET",
        path_template: "/v1/library/files/{file_id}",
        requires_auth: true,
        body_kind: BodyKind::Empty,
        request_schema: "-",
        response_schema: "LibraryFileDetailResponse",
        success_status: 200,
        idempotent: false,
    },
    Operation {
        id: "get_library_resources",
        method: "GET",
        path_template: "/v1/library/resources",
        requires_auth: true,
        body_kind: BodyKind::Empty,
        request_schema: "-",
        response_schema: "LibraryResourcePageResponse",
        success_status: 200,
        idempotent: false,
    },
    Operation {
        id: "get_library_tree",
        method: "GET",
        path_template: "/v1/library/tree",
        requires_auth: true,
        body_kind: BodyKind::Empty,
        request_schema: "-",
        response_schema: "LibraryTreeResponse",
        success_status: 200,
        idempotent: false,
    },
    Operation {
        id: "get_runtime_settings",
        method: "GET",
        path_template: "/v1/settings/runtime",
        requires_auth: true,
        body_kind: BodyKind::Empty,
        request_schema: "-",
        response_schema: "RuntimeSettingsResponse",
        success_status: 200,
        idempotent: false,
    },
    Operation {
        id: "get_search_settings",
        method: "GET",
        path_template: "/v1/settings/search",
        requires_auth: true,
        body_kind: BodyKind::Empty,
        request_schema: "-",
        response_schema: "SearchSettingsResponse",
        success_status: 200,
        idempotent: false,
    },
    Operation {
        id: "get_task",
        method: "GET",
        path_template: "/v1/tasks/{task_id}",
        requires_auth: true,
        body_kind: BodyKind::Empty,
        request_schema: "-",
        response_schema: "TaskResponse",
        success_status: 200,
        idempotent: false,
    },
    Operation {
        id: "get_translation_settings",
        method: "GET",
        path_template: "/v1/settings/translation",
        requires_auth: true,
        body_kind: BodyKind::Empty,
        request_schema: "-",
        response_schema: "TranslationSettingsResponse",
        success_status: 200,
        idempotent: false,
    },
    Operation {
        id: "healthz",
        method: "GET",
        path_template: "/healthz",
        requires_auth: false,
        body_kind: BodyKind::Empty,
        request_schema: "-",
        response_schema: "HealthResponse",
        success_status: 200,
        idempotent: false,
    },
    Operation {
        id: "import_group_library_file_url",
        method: "POST",
        path_template: "/v1/groups/by-path/{group_path}/library/files/import-url",
        requires_auth: true,
        body_kind: BodyKind::Json,
        request_schema: "ImportLibraryFileFromUrlRequest",
        response_schema: "TaskRef",
        success_status: 202,
        idempotent: false,
    },
    Operation {
        id: "list_admin_users",
        method: "GET",
        path_template: "/v1/admin/users",
        requires_auth: true,
        body_kind: BodyKind::Empty,
        request_schema: "-",
        response_schema: "AdminUserPageResponse",
        success_status: 200,
        idempotent: false,
    },
    Operation {
        id: "list_child_groups",
        method: "GET",
        path_template: "/v1/groups/by-path/{group_path}/children",
        requires_auth: true,
        body_kind: BodyKind::Empty,
        request_schema: "-",
        response_schema: "GroupPageResponse",
        success_status: 200,
        idempotent: false,
    },
    Operation {
        id: "list_document_extraction_jobs",
        method: "GET",
        path_template: "/v1/groups/by-path/{group_path}/documents/{document_id}/extractions",
        requires_auth: true,
        body_kind: BodyKind::Empty,
        request_schema: "-",
        response_schema: "ExtractionJobsResponse",
        success_status: 200,
        idempotent: false,
    },
    Operation {
        id: "list_document_translation_jobs",
        method: "GET",
        path_template: "/v1/groups/by-path/{group_path}/documents/{document_id}/translations",
        requires_auth: true,
        body_kind: BodyKind::Empty,
        request_schema: "-",
        response_schema: "TranslationJobsResponse",
        success_status: 200,
        idempotent: false,
    },
    Operation {
        id: "list_extraction_templates",
        method: "GET",
        path_template: "/v1/groups/by-path/{group_path}/extraction-templates",
        requires_auth: true,
        body_kind: BodyKind::Empty,
        request_schema: "-",
        response_schema: "array<ExtractionTemplateResponse>",
        success_status: 200,
        idempotent: false,
    },
    Operation {
        id: "list_group_members",
        method: "GET",
        path_template: "/v1/groups/by-path/{group_path}/members",
        requires_auth: true,
        body_kind: BodyKind::Empty,
        request_schema: "-",
        response_schema: "GroupMemberPageResponse",
        success_status: 200,
        idempotent: false,
    },
    Operation {
        id: "list_groups",
        method: "GET",
        path_template: "/v1/groups",
        requires_auth: true,
        body_kind: BodyKind::Empty,
        request_schema: "-",
        response_schema: "GroupPageResponse",
        success_status: 200,
        idempotent: false,
    },
    Operation {
        id: "list_metadata_indexes",
        method: "GET",
        path_template: "/v1/groups/by-path/{group_path}/metadata-indexes",
        requires_auth: true,
        body_kind: BodyKind::Empty,
        request_schema: "-",
        response_schema: "MetadataIndexPageResponse",
        success_status: 200,
        idempotent: false,
    },
    Operation {
        id: "list_personal_access_tokens",
        method: "GET",
        path_template: "/v1/auth/personal-access-tokens",
        requires_auth: true,
        body_kind: BodyKind::Empty,
        request_schema: "-",
        response_schema: "PersonalAccessTokenPageResponse",
        success_status: 200,
        idempotent: false,
    },
    Operation {
        id: "list_source_connections",
        method: "GET",
        path_template: "/v1/source-connections",
        requires_auth: true,
        body_kind: BodyKind::Empty,
        request_schema: "-",
        response_schema: "array<SourceConnectionResponse>",
        success_status: 200,
        idempotent: false,
    },
    Operation {
        id: "list_sources",
        method: "GET",
        path_template: "/v1/sources",
        requires_auth: true,
        body_kind: BodyKind::Empty,
        request_schema: "-",
        response_schema: "SourcePageResponse",
        success_status: 200,
        idempotent: false,
    },
    Operation {
        id: "list_task_items",
        method: "GET",
        path_template: "/v1/tasks/{task_id}/items",
        requires_auth: true,
        body_kind: BodyKind::Empty,
        request_schema: "-",
        response_schema: "TaskItemsResponse",
        success_status: 200,
        idempotent: false,
    },
    Operation {
        id: "list_tasks",
        method: "GET",
        path_template: "/v1/tasks",
        requires_auth: true,
        body_kind: BodyKind::Empty,
        request_schema: "-",
        response_schema: "TaskPageResponse",
        success_status: 200,
        idempotent: false,
    },
    Operation {
        id: "list_translation_providers",
        method: "GET",
        path_template: "/v1/settings/translation/providers",
        requires_auth: true,
        body_kind: BodyKind::Empty,
        request_schema: "-",
        response_schema: "TranslationProviderPageResponse",
        success_status: 200,
        idempotent: false,
    },
    Operation {
        id: "login",
        method: "POST",
        path_template: "/v1/auth/login",
        requires_auth: false,
        body_kind: BodyKind::Json,
        request_schema: "AuthLoginRequest",
        response_schema: "-",
        success_status: 204,
        idempotent: false,
    },
    Operation {
        id: "logout",
        method: "POST",
        path_template: "/v1/auth/logout",
        requires_auth: false,
        body_kind: BodyKind::Empty,
        request_schema: "-",
        response_schema: "-",
        success_status: 204,
        idempotent: false,
    },
    Operation {
        id: "me",
        method: "GET",
        path_template: "/v1/auth/me",
        requires_auth: true,
        body_kind: BodyKind::Empty,
        request_schema: "-",
        response_schema: "AuthMeResponse",
        success_status: 200,
        idempotent: false,
    },
    Operation {
        id: "move_group",
        method: "POST",
        path_template: "/v1/groups/by-path/{group_path}/move",
        requires_auth: true,
        body_kind: BodyKind::Json,
        request_schema: "MoveGroupRequest",
        response_schema: "GroupResponse",
        success_status: 200,
        idempotent: false,
    },
    Operation {
        id: "move_group_library_file",
        method: "POST",
        path_template: "/v1/groups/by-path/{group_path}/library/files/{file_id}/move",
        requires_auth: true,
        body_kind: BodyKind::Json,
        request_schema: "MoveFileRequest",
        response_schema: "LibraryFileDetailResponse",
        success_status: 200,
        idempotent: false,
    },
    Operation {
        id: "move_group_library_folder",
        method: "POST",
        path_template: "/v1/groups/by-path/{group_path}/library/folders/{folder_id}/move",
        requires_auth: true,
        body_kind: BodyKind::Json,
        request_schema: "MoveFolderRequest",
        response_schema: "LibraryFolderResponse",
        success_status: 200,
        idempotent: false,
    },
    Operation {
        id: "move_library_file",
        method: "POST",
        path_template: "/v1/library/files/{file_id}/move",
        requires_auth: true,
        body_kind: BodyKind::Json,
        request_schema: "MoveFileRequest",
        response_schema: "LibraryFileDetailResponse",
        success_status: 200,
        idempotent: false,
    },
    Operation {
        id: "move_library_folder",
        method: "POST",
        path_template: "/v1/library/folders/{folder_id}/move",
        requires_auth: true,
        body_kind: BodyKind::Json,
        request_schema: "MoveFolderRequest",
        response_schema: "LibraryFolderResponse",
        success_status: 200,
        idempotent: false,
    },
    Operation {
        id: "prepare_group_library_upload",
        method: "POST",
        path_template: "/v1/groups/by-path/{group_path}/library/files/prepare-upload",
        requires_auth: true,
        body_kind: BodyKind::Json,
        request_schema: "PrepareLibraryUploadRequest",
        response_schema: "PrepareLibraryUploadResponse",
        success_status: 200,
        idempotent: false,
    },
    Operation {
        id: "quarantine_stale_submitting",
        method: "POST",
        path_template: "/v1/admin/tasks/quarantine-submitting",
        requires_auth: true,
        body_kind: BodyKind::Json,
        request_schema: "QuarantineStaleSubmittingRequest",
        response_schema: "QuarantineStaleSubmittingResponse",
        success_status: 200,
        idempotent: false,
    },
    Operation {
        id: "query_group_documents",
        method: "POST",
        path_template: "/v1/groups/by-path/{group_path}/documents/query",
        requires_auth: true,
        body_kind: BodyKind::Json,
        request_schema: "DocumentQueryRequest",
        response_schema: "DocumentQueryResponse",
        success_status: 200,
        idempotent: false,
    },
    Operation {
        id: "queue_docling_recovery",
        method: "POST",
        path_template: "/v1/admin/tasks/{task_id}/recover/queue",
        requires_auth: true,
        body_kind: BodyKind::Json,
        request_schema: "QueueDoclingRecoveryRequest",
        response_schema: "QueueDoclingRecoveryResponse",
        success_status: 200,
        idempotent: false,
    },
    Operation {
        id: "rebuild_document_extractions",
        method: "POST",
        path_template: "/v1/groups/by-path/{group_path}/documents/{document_id}/extractions/rebuild",
        requires_auth: true,
        body_kind: BodyKind::Json,
        request_schema: "RebuildDocumentExtractionsRequest",
        response_schema: "ExtractionJobsResponse",
        success_status: 200,
        idempotent: false,
    },
    Operation {
        id: "rebuild_document_translations",
        method: "POST",
        path_template: "/v1/groups/by-path/{group_path}/documents/{document_id}/translations/rebuild",
        requires_auth: true,
        body_kind: BodyKind::Json,
        request_schema: "RebuildDocumentTranslationsRequest",
        response_schema: "TaskRef",
        success_status: 202,
        idempotent: false,
    },
    Operation {
        id: "recover_docling_task",
        method: "POST",
        path_template: "/v1/admin/tasks/{task_id}/recover",
        requires_auth: true,
        body_kind: BodyKind::Json,
        request_schema: "RecoverDoclingTaskRequest",
        response_schema: "RecoverDoclingTaskResponse",
        success_status: 200,
        idempotent: false,
    },
    Operation {
        id: "release_group_library_file_source",
        method: "POST",
        path_template: "/v1/groups/by-path/{group_path}/library/files/{file_id}/release-source",
        requires_auth: true,
        body_kind: BodyKind::Empty,
        request_schema: "-",
        response_schema: "LibraryFileDetailResponse",
        success_status: 200,
        idempotent: false,
    },
    Operation {
        id: "rerun_task",
        method: "POST",
        path_template: "/v1/tasks/{task_id}/rerun",
        requires_auth: true,
        body_kind: BodyKind::Empty,
        request_schema: "-",
        response_schema: "RerunTaskResponse",
        success_status: 202,
        idempotent: false,
    },
    Operation {
        id: "reset_admin_user_password",
        method: "POST",
        path_template: "/v1/admin/users/{login_name}/reset-password",
        requires_auth: true,
        body_kind: BodyKind::Json,
        request_schema: "ResetAdminUserPasswordRequest",
        response_schema: "AdminUserResponse",
        success_status: 200,
        idempotent: false,
    },
    Operation {
        id: "restore_task",
        method: "POST",
        path_template: "/v1/tasks/{task_id}/restore",
        requires_auth: true,
        body_kind: BodyKind::Empty,
        request_schema: "-",
        response_schema: "TaskResponse",
        success_status: 200,
        idempotent: false,
    },
    Operation {
        id: "retry_metadata_index",
        method: "POST",
        path_template: "/v1/groups/by-path/{group_path}/metadata-indexes/{index_id}/retry",
        requires_auth: true,
        body_kind: BodyKind::Empty,
        request_schema: "-",
        response_schema: "MetadataIndexResponse",
        success_status: 200,
        idempotent: false,
    },
    Operation {
        id: "retry_task",
        method: "POST",
        path_template: "/v1/tasks/{task_id}/retry",
        requires_auth: true,
        body_kind: BodyKind::Empty,
        request_schema: "-",
        response_schema: "TaskRetryResponse",
        success_status: 202,
        idempotent: false,
    },
    Operation {
        id: "revoke_personal_access_token",
        method: "DELETE",
        path_template: "/v1/auth/personal-access-tokens/{token_id}",
        requires_auth: true,
        body_kind: BodyKind::Empty,
        request_schema: "-",
        response_schema: "-",
        success_status: 204,
        idempotent: false,
    },
    Operation {
        id: "search",
        method: "POST",
        path_template: "/v1/search",
        requires_auth: true,
        body_kind: BodyKind::Json,
        request_schema: "SearchRequest",
        response_schema: "SearchResponse",
        success_status: 200,
        idempotent: false,
    },
    Operation {
        id: "search_groups",
        method: "GET",
        path_template: "/v1/groups/search",
        requires_auth: true,
        body_kind: BodyKind::Empty,
        request_schema: "-",
        response_schema: "array<GroupResponse>",
        success_status: 200,
        idempotent: false,
    },
    Operation {
        id: "search_stream",
        method: "GET",
        path_template: "/v1/search/stream",
        requires_auth: true,
        body_kind: BodyKind::Empty,
        request_schema: "-",
        response_schema: "-",
        success_status: 200,
        idempotent: false,
    },
    Operation {
        id: "search_user_directory",
        method: "GET",
        path_template: "/v1/user-directory",
        requires_auth: true,
        body_kind: BodyKind::Empty,
        request_schema: "-",
        response_schema: "array<UserDirectoryEntryResponse>",
        success_status: 200,
        idempotent: false,
    },
    Operation {
        id: "submit_delete_batch",
        method: "POST",
        path_template: "/v1/groups/by-path/{group_path}/batch/delete",
        requires_auth: true,
        body_kind: BodyKind::Json,
        request_schema: "DeleteBatchRequest",
        response_schema: "TaskRef",
        success_status: 202,
        idempotent: true,
    },
    Operation {
        id: "submit_file_batch",
        method: "POST",
        path_template: "/v1/groups/by-path/{group_path}/batch/file",
        requires_auth: true,
        body_kind: BodyKind::Json,
        request_schema: "FileBatchRequest",
        response_schema: "TaskRef",
        success_status: 202,
        idempotent: true,
    },
    Operation {
        id: "submit_task",
        method: "POST",
        path_template: "/v1/tasks",
        requires_auth: true,
        body_kind: BodyKind::Json,
        request_schema: "TaskSubmitRequest",
        response_schema: "TaskRef",
        success_status: 202,
        idempotent: true,
    },
    Operation {
        id: "submit_text_batch",
        method: "POST",
        path_template: "/v1/groups/by-path/{group_path}/batch/text",
        requires_auth: true,
        body_kind: BodyKind::Json,
        request_schema: "TextBatchRequest",
        response_schema: "TaskRef",
        success_status: 202,
        idempotent: true,
    },
    Operation {
        id: "submit_url_batch",
        method: "POST",
        path_template: "/v1/groups/by-path/{group_path}/batch/url",
        requires_auth: true,
        body_kind: BodyKind::Json,
        request_schema: "UrlBatchRequest",
        response_schema: "TaskRef",
        success_status: 202,
        idempotent: true,
    },
    Operation {
        id: "submit_vector_index_rebuild",
        method: "POST",
        path_template: "/v1/settings/runtime/vector-index/rebuild",
        requires_auth: true,
        body_kind: BodyKind::Empty,
        request_schema: "-",
        response_schema: "TaskRef",
        success_status: 202,
        idempotent: true,
    },
    Operation {
        id: "sync_group_source_folder",
        method: "POST",
        path_template: "/v1/groups/by-path/{group_path}/source-folders/{folder_id}/sync",
        requires_auth: true,
        body_kind: BodyKind::Empty,
        request_schema: "-",
        response_schema: "TaskRef",
        success_status: 202,
        idempotent: false,
    },
    Operation {
        id: "sync_source",
        method: "POST",
        path_template: "/v1/sources/{source_key}/sync",
        requires_auth: true,
        body_kind: BodyKind::Empty,
        request_schema: "-",
        response_schema: "TaskRef",
        success_status: 202,
        idempotent: false,
    },
    Operation {
        id: "test_s3_connection",
        method: "POST",
        path_template: "/v1/settings/runtime/s3/test",
        requires_auth: true,
        body_kind: BodyKind::Json,
        request_schema: "UpdateRuntimeS3Settings",
        response_schema: "-",
        success_status: 204,
        idempotent: false,
    },
    Operation {
        id: "test_valkey_connection",
        method: "POST",
        path_template: "/v1/settings/runtime/valkey/test",
        requires_auth: true,
        body_kind: BodyKind::Json,
        request_schema: "TestRuntimeValkeyRequest",
        response_schema: "-",
        success_status: 204,
        idempotent: false,
    },
    Operation {
        id: "trash_task",
        method: "POST",
        path_template: "/v1/tasks/{task_id}/trash",
        requires_auth: true,
        body_kind: BodyKind::Empty,
        request_schema: "-",
        response_schema: "TaskResponse",
        success_status: 200,
        idempotent: false,
    },
    Operation {
        id: "update_admin_user",
        method: "PATCH",
        path_template: "/v1/admin/users/{login_name}",
        requires_auth: true,
        body_kind: BodyKind::Json,
        request_schema: "UpdateAdminUserRequest",
        response_schema: "AdminUserResponse",
        success_status: 200,
        idempotent: false,
    },
    Operation {
        id: "update_docling_settings",
        method: "PUT",
        path_template: "/v1/settings/docling",
        requires_auth: true,
        body_kind: BodyKind::Json,
        request_schema: "UpdateDoclingSettingsRequest",
        response_schema: "DoclingSettingsResponse",
        success_status: 200,
        idempotent: false,
    },
    Operation {
        id: "update_group",
        method: "PATCH",
        path_template: "/v1/groups/by-path/{group_path}",
        requires_auth: true,
        body_kind: BodyKind::Json,
        request_schema: "UpdateGroupRequest",
        response_schema: "GroupResponse",
        success_status: 200,
        idempotent: false,
    },
    Operation {
        id: "update_group_source_folder_config",
        method: "PUT",
        path_template: "/v1/groups/by-path/{group_path}/source-folders/{folder_id}/config",
        requires_auth: true,
        body_kind: BodyKind::Json,
        request_schema: "SourceConfigInput",
        response_schema: "SourceFolderResponse",
        success_status: 200,
        idempotent: false,
    },
    Operation {
        id: "update_group_translation_settings",
        method: "PUT",
        path_template: "/v1/groups/by-path/{group_path}/translation-settings",
        requires_auth: true,
        body_kind: BodyKind::Json,
        request_schema: "UpdateGroupTranslationSettingsRequest",
        response_schema: "GroupTranslationSettingsResponse",
        success_status: 200,
        idempotent: false,
    },
    Operation {
        id: "update_metadata_index",
        method: "PUT",
        path_template: "/v1/groups/by-path/{group_path}/metadata-indexes/{index_id}",
        requires_auth: true,
        body_kind: BodyKind::Json,
        request_schema: "UpdateMetadataIndexRequest",
        response_schema: "MetadataIndexResponse",
        success_status: 200,
        idempotent: false,
    },
    Operation {
        id: "update_runtime_settings",
        method: "PUT",
        path_template: "/v1/settings/runtime",
        requires_auth: true,
        body_kind: BodyKind::Json,
        request_schema: "UpdateRuntimeSettingsRequest",
        response_schema: "RuntimeSettingsResponse",
        success_status: 200,
        idempotent: false,
    },
    Operation {
        id: "update_search_settings",
        method: "PUT",
        path_template: "/v1/settings/search",
        requires_auth: true,
        body_kind: BodyKind::Json,
        request_schema: "CanonicalUpdateSearchSettingsRequest",
        response_schema: "SearchSettingsResponse",
        success_status: 200,
        idempotent: false,
    },
    Operation {
        id: "update_source",
        method: "PUT",
        path_template: "/v1/sources/{source_key}",
        requires_auth: true,
        body_kind: BodyKind::Json,
        request_schema: "SourceConfigInput",
        response_schema: "SourceStatus",
        success_status: 200,
        idempotent: false,
    },
    Operation {
        id: "update_source_connection",
        method: "PUT",
        path_template: "/v1/source-connections",
        requires_auth: true,
        body_kind: BodyKind::Json,
        request_schema: "UpsertSourceConnectionRequest",
        response_schema: "SourceConnectionResponse",
        success_status: 200,
        idempotent: false,
    },
    Operation {
        id: "update_translation_settings",
        method: "PUT",
        path_template: "/v1/settings/translation",
        requires_auth: true,
        body_kind: BodyKind::Json,
        request_schema: "UpdateTranslationSettingsRequest",
        response_schema: "TranslationSettingsResponse",
        success_status: 200,
        idempotent: false,
    },
    Operation {
        id: "upload_group_library_files",
        method: "POST",
        path_template: "/v1/groups/by-path/{group_path}/library/files/upload",
        requires_auth: true,
        body_kind: BodyKind::Multipart,
        request_schema: "multipart-form",
        response_schema: "TaskRef",
        success_status: 202,
        idempotent: false,
    },
    Operation {
        id: "upload_library_files",
        method: "POST",
        path_template: "/v1/library/files/upload",
        requires_auth: true,
        body_kind: BodyKind::Multipart,
        request_schema: "multipart-form",
        response_schema: "TaskRef",
        success_status: 202,
        idempotent: false,
    },
    Operation {
        id: "upsert_extraction_template",
        method: "PUT",
        path_template: "/v1/groups/by-path/{group_path}/extraction-templates",
        requires_auth: true,
        body_kind: BodyKind::Json,
        request_schema: "ExtractionTemplateInput",
        response_schema: "ExtractionTemplateResponse",
        success_status: 200,
        idempotent: false,
    },
    Operation {
        id: "upsert_group_library_text",
        method: "PUT",
        path_template: "/v1/groups/by-path/{group_path}/library/texts",
        requires_auth: true,
        body_kind: BodyKind::Json,
        request_schema: "UpsertLibraryTextRequest",
        response_schema: "TaskRef",
        success_status: 202,
        idempotent: false,
    },
    Operation {
        id: "upsert_group_member",
        method: "POST",
        path_template: "/v1/groups/by-path/{group_path}/members",
        requires_auth: true,
        body_kind: BodyKind::Json,
        request_schema: "UpsertMembershipRequest",
        response_schema: "-",
        success_status: 204,
        idempotent: false,
    },
];
