INSERT INTO context69.docling_settings (
    singleton,
    base_url,
    timeout_secs,
    poll_interval_secs,
    task_timeout_secs,
    max_inflight,
    pdf_backend,
    images_scale,
    image_export_mode,
    do_ocr,
    force_ocr,
    ocr_engine,
    ocr_lang,
    do_code_enrichment,
    do_formula_enrichment,
    do_picture_description,
    openai_base_url,
    api_key,
    vlm_pipeline_model,
    picture_description_model,
    code_formula_model,
    picture_description_preset,
    updated_at
)
VALUES (
    TRUE,
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17,
    $18,
    $19,
    $20,
    $21,
    now()
)
ON CONFLICT (singleton) DO UPDATE
SET base_url = EXCLUDED.base_url,
    timeout_secs = EXCLUDED.timeout_secs,
    poll_interval_secs = EXCLUDED.poll_interval_secs,
    task_timeout_secs = EXCLUDED.task_timeout_secs,
    max_inflight = EXCLUDED.max_inflight,
    pdf_backend = EXCLUDED.pdf_backend,
    images_scale = EXCLUDED.images_scale,
    image_export_mode = EXCLUDED.image_export_mode,
    do_ocr = EXCLUDED.do_ocr,
    force_ocr = EXCLUDED.force_ocr,
    ocr_engine = EXCLUDED.ocr_engine,
    ocr_lang = EXCLUDED.ocr_lang,
    do_code_enrichment = EXCLUDED.do_code_enrichment,
    do_formula_enrichment = EXCLUDED.do_formula_enrichment,
    do_picture_description = EXCLUDED.do_picture_description,
    openai_base_url = EXCLUDED.openai_base_url,
    api_key = EXCLUDED.api_key,
    vlm_pipeline_model = EXCLUDED.vlm_pipeline_model,
    picture_description_model = EXCLUDED.picture_description_model,
    code_formula_model = EXCLUDED.code_formula_model,
    picture_description_preset = EXCLUDED.picture_description_preset,
    updated_at = now()
RETURNING
    base_url,
    timeout_secs,
    poll_interval_secs,
    task_timeout_secs,
    max_inflight,
    pdf_backend,
    images_scale,
    image_export_mode,
    do_ocr,
    force_ocr,
    ocr_engine,
    ocr_lang,
    do_code_enrichment,
    do_formula_enrichment,
    do_picture_description,
    openai_base_url,
    api_key,
    vlm_pipeline_model,
    picture_description_model,
    code_formula_model,
    picture_description_preset
