[package]
name = "context69-namespace-http"
version = "0.1.0"
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
axum.workspace = true
context69-contracts-core.workspace = true
context69-contracts-namespace.workspace = true
context69-http-support.workspace = true
serde = { workspace = true, features = ["derive"] }
utoipa.workspace = true
